#ifndef BUFFERCLEAROBEYSTENCIL_COMMON_HLSLI_INCLUDE_GUARD
#define BUFFERCLEAROBEYSTENCIL_COMMON_HLSLI_INCLUDE_GUARD

[[vk::constant_id(SPEC_CONST_ID_BASE_VS + 0)]] const bool USESCOLOR = false;

#endif // BUFFERCLEAROBEYSTENCIL_COMMON_HLSLI_INCLUDE_GUARD
